apiVersion: batch/v1
kind: CronJob
metadata:
  name: petrosa-usa-get-candles-m30
spec:
  schedule: "2,32 15-22 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: petrosa-apps-jobs
            image: yurisa2/petrosa-apps-jobs:v0.0.14
            env:
              - name: COL_NAME
                value: "candles_m30"
              - name: MINUTES
                value: "30"
              - name: VERSION
                value: "0.0.14"
              - name: NEW_RELIC_APP_NAME
                value: "petrosa-usa-get-candles-m30"
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: petrosa-apps-secret
                    key: MONGO_URI
                    optional: false
              - name: KAFKA_ADDRESS
                valueFrom:
                  secretKeyRef:
                    name: petrosa-apps-secret
                    key: KAFKA_ADDRESS
                    optional: false
              - name: NEW_RELIC_LICENSE_KEY
                valueFrom:
                  secretKeyRef:
                    name: petrosa-apps-secret
                    key: NEW_RELIC_LICENSE_KEY
                    optional: false
              - name: NEW_RELIC_LICENSE_KEY
                valueFrom:
                  secretKeyRef:
                    name: petrosa-apps-secret
                    key: NEW_RELIC_LICENSE_KEY
                    optional: false

            imagePullPolicy: Always
            command: ["newrelic-admin",  "run-python"]
            args: ["./petrosa_usa_get_candles/driver.py"]
          restartPolicy: OnFailure
